version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development  # Change to 'production' in a production environment
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0  # Allow access from outside the container
    
